### PR TITLE
Update to appinspect url

### PR DESCRIPTION
**Pull request by twesty1987**

### CODE REVIEW

**Review by billford — APPROVED** [review]
Bah, this is going to make it a maintenance issue, thanks for the PR, I am merging now.

**Comment by hypnot0ad** [comment]
are you looking to use 2.0.0 specifically? or would using "latest" instead reduce the maintenance headache?

**Comment by billford** [comment]
Well I would love to use latest but last time I looked they seem to have broken that hence the pegging to 2.0. I will check again to see if it's working now and make the appropriate changes. Thanks

**Comment by billford** [comment]
YAY, it does work now. That's been updated, also added a python3 .yml file

**Pull request merged**
